CREATE TABLE IF NOT EXISTS CATEGORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    PRICE DOUBLE,
    CATEGORYID INT,
    FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(ID)
);